export const autoCompleteStaticData = {
  hits: [
    {
      id: 2,
      name: "Dubai",
      name_l1: "دبي",
      externalID: "5002",
      slug: "/dubai",
      slug_l1: "/dubai",
      _geoloc: {
        lat: 25.2017993927,
        lng: 55.285301208496,
      },
      geography: {
        lat: 25.2017993927,
        lng: 55.285301208496,
      },
      level: 1,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
      ],
      adCount: 134619,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "5002",
      roles: null,
      objectID: "2",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5002",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 10,
      name: "Downtown Dubai",
      name_l1: "وسط مدينة دبي",
      externalID: "6901",
      slug: "/dubai/downtown-dubai",
      slug_l1: "/dubai/downtown-dubai",
      _geoloc: {
        lat: 25.194213,
        lng: 55.277412,
      },
      geography: {
        lat: 25.194213,
        lng: 55.277412,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 10,
          level: 2,
          externalID: "6901",
          name: "Downtown Dubai",
          name_l1: "وسط مدينة دبي",
          slug: "/dubai/downtown-dubai",
          slug_l1: "/dubai/downtown-dubai",
        },
      ],
      adCount: 10862,
      aliases: ["Dubai Downtown", "Down Town Dubai", "Downtown"],
      type: null,
      hasBuilding: false,
      trackID: "6901",
      roles: null,
      objectID: "10",
      _highlightResult: {
        name: {
          value: "Downtown <em>Duba</em>i",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "6901",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "6901",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/downtown-<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "<em>Duba</em>i Downtown",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "Down Town <em>Duba</em>i",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "Downtown",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 36,
      name: "Dubai Marina",
      name_l1: "دبي مارينا",
      externalID: "5003",
      slug: "/dubai/dubai-marina",
      slug_l1: "/dubai/dubai-marina",
      _geoloc: {
        lat: 25.078399658203,
        lng: 55.142398834229,
      },
      geography: {
        lat: 25.078399658203,
        lng: 55.142398834229,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 36,
          level: 2,
          externalID: "5003",
          name: "Dubai Marina",
          name_l1: "دبي مارينا",
          slug: "/dubai/dubai-marina",
          slug_l1: "/dubai/dubai-marina",
        },
      ],
      adCount: 8532,
      aliases: ["Marina Dubai", "Marsa Dubai", "Dubai Marsa"],
      type: null,
      hasBuilding: false,
      trackID: "5003",
      roles: null,
      objectID: "36",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Marina",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5003",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5003",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-marina",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "Marina <em>Duba</em>i",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "Marsa <em>Duba</em>i",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "<em>Duba</em>i Marsa",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
        ],
      },
    },
    {
      id: 53,
      name: "Dubai Hills Estate",
      name_l1: "دبي هيلز استيت",
      externalID: "8288",
      slug: "/dubai/dubai-hills-estate",
      slug_l1: "/dubai/dubai-hills-estate",
      _geoloc: {
        lat: 25.112660550438,
        lng: 55.257525443594,
      },
      geography: {
        lat: 25.112660550438,
        lng: 55.257525443594,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 53,
          level: 2,
          externalID: "8288",
          name: "Dubai Hills Estate",
          name_l1: "دبي هيلز استيت",
          slug: "/dubai/dubai-hills-estate",
          slug_l1: "/dubai/dubai-hills-estate",
        },
      ],
      adCount: 3912,
      aliases: ["Dubai Hills"],
      type: null,
      hasBuilding: false,
      trackID: "8288",
      roles: null,
      objectID: "53",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Hills Estate",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "8288",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "8288",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-hills-estate",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "<em>Duba</em>i Hills",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
        ],
      },
    },
    {
      id: 51,
      name: "Dubailand",
      name_l1: "دبي لاند",
      externalID: "5746",
      slug: "/dubai/dubailand",
      slug_l1: "/dubai/dubailand",
      _geoloc: {
        lat: 25.0347325,
        lng: 55.361114070491,
      },
      geography: {
        lat: 25.0347325,
        lng: 55.361114070491,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 51,
          level: 2,
          externalID: "5746",
          name: "Dubailand",
          name_l1: "دبي لاند",
          slug: "/dubai/dubailand",
          slug_l1: "/dubai/dubailand",
        },
      ],
      adCount: 3845,
      aliases: ["Dubai Land"],
      type: null,
      hasBuilding: false,
      trackID: "5746",
      roles: null,
      objectID: "51",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>iland",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5746",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5746",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>iland",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "<em>Duba</em>i Land",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
        ],
      },
    },
    {
      id: 242,
      name: "Dubai Creek Harbour",
      name_l1: "مرسى خور دبي",
      externalID: "8617",
      slug: "/dubai/the-lagoons/dubai-creek-harbour",
      slug_l1: "/dubai/the-lagoons/dubai-creek-harbour",
      _geoloc: {
        lat: 25.199751,
        lng: 55.358155,
      },
      geography: {
        lat: 25.199751,
        lng: 55.358155,
      },
      level: 3,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 241,
          level: 2,
          externalID: "5539",
          name: "The Lagoons",
          name_l1: "ذا لاجونز",
          slug: "/dubai/the-lagoons",
          slug_l1: "/dubai/the-lagoons",
        },
        {
          id: 242,
          level: 3,
          externalID: "8617",
          name: "Dubai Creek Harbour",
          name_l1: "مرسى خور دبي",
          slug: "/dubai/the-lagoons/dubai-creek-harbour",
          slug_l1: "/dubai/the-lagoons/dubai-creek-harbour",
        },
      ],
      adCount: 3010,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "8617",
      roles: null,
      objectID: "242",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Creek Harbour",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "8617",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5539",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/the-lagoons",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "8617",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/the-lagoons/<em>duba</em>i-creek-harbour",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 345,
      name: "Bur Dubai",
      name_l1: "بر دبي",
      externalID: "6796",
      slug: "/dubai/bur-dubai",
      slug_l1: "/dubai/bur-dubai",
      _geoloc: {
        lat: 25.254371037712,
        lng: 55.283216390258,
      },
      geography: {
        lat: 25.254371037712,
        lng: 55.283216390258,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 345,
          level: 2,
          externalID: "6796",
          name: "Bur Dubai",
          name_l1: "بر دبي",
          slug: "/dubai/bur-dubai",
          slug_l1: "/dubai/bur-dubai",
        },
      ],
      adCount: 2626,
      aliases: ["Burdubai"],
      type: null,
      hasBuilding: false,
      trackID: "6796",
      roles: null,
      objectID: "345",
      _highlightResult: {
        name: {
          value: "Bur <em>Duba</em>i",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "6796",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "6796",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/bur-<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "Burdubai",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 67,
      name: "Dubai Sports City",
      name_l1: "مدينة دبي الرياضية",
      externalID: "5274",
      slug: "/dubai/dubai-sports-city",
      slug_l1: "/dubai/dubai-sports-city",
      _geoloc: {
        lat: 25.036865,
        lng: 55.226703790815,
      },
      geography: {
        lat: 25.036865,
        lng: 55.226703790815,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 67,
          level: 2,
          externalID: "5274",
          name: "Dubai Sports City",
          name_l1: "مدينة دبي الرياضية",
          slug: "/dubai/dubai-sports-city",
          slug_l1: "/dubai/dubai-sports-city",
        },
      ],
      adCount: 2113,
      aliases: ["Sports City Dubai", "Sports City", "Sport City", "DSC"],
      type: null,
      hasBuilding: false,
      trackID: "5274",
      roles: null,
      objectID: "67",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Sports City",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5274",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5274",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-sports-city",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "Sports City <em>Duba</em>i",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "Sports City",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "Sport City",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "DSC",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 3512,
      name: "Dubai Harbour",
      name_l1: "دبي هاربور‬",
      externalID: "11876",
      slug: "/dubai/dubai-harbour",
      slug_l1: "/dubai/dubai-harbour",
      _geoloc: {
        lat: 25.100011,
        lng: 55.141959,
      },
      geography: {
        lat: 25.100011,
        lng: 55.141959,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 3512,
          level: 2,
          externalID: "11876",
          name: "Dubai Harbour",
          name_l1: "دبي هاربور‬",
          slug: "/dubai/dubai-harbour",
          slug_l1: "/dubai/dubai-harbour",
        },
      ],
      adCount: 1855,
      aliases: ["Dubai Harbour Emaar"],
      type: null,
      hasBuilding: false,
      trackID: "11876",
      roles: null,
      objectID: "3512",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Harbour",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "11876",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "11876",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-harbour",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "<em>Duba</em>i Harbour Emaar",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
        ],
      },
    },
    {
      id: 295,
      name: "Dubai Silicon Oasis",
      name_l1: "واحة دبي للسيليكون",
      externalID: "5361",
      slug: "/dubai/dubai-silicon-oasis",
      slug_l1: "/dubai/dubai-silicon-oasis",
      _geoloc: {
        lat: 25.121001948708,
        lng: 55.379784107208,
      },
      geography: {
        lat: 25.121001948708,
        lng: 55.379784107208,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 295,
          level: 2,
          externalID: "5361",
          name: "Dubai Silicon Oasis",
          name_l1: "واحة دبي للسيليكون",
          slug: "/dubai/dubai-silicon-oasis",
          slug_l1: "/dubai/dubai-silicon-oasis",
        },
      ],
      adCount: 1730,
      aliases: ["DSO", "Silicon Oasis"],
      type: null,
      hasBuilding: false,
      trackID: "5361",
      roles: null,
      objectID: "295",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Silicon Oasis",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5361",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5361",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-silicon-oasis",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "DSO",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "Silicon Oasis",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 3355,
      name: "Dubai South",
      name_l1: "دبي الجنوب",
      externalID: "8881",
      slug: "/dubai/dubai-south",
      slug_l1: "/dubai/dubai-south",
      _geoloc: {
        lat: 24.904965962428,
        lng: 55.165958404541,
      },
      geography: {
        lat: 24.904965962428,
        lng: 55.165958404541,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 3355,
          level: 2,
          externalID: "8881",
          name: "Dubai South",
          name_l1: "دبي الجنوب",
          slug: "/dubai/dubai-south",
          slug_l1: "/dubai/dubai-south",
        },
      ],
      adCount: 1643,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "8881",
      roles: null,
      objectID: "3355",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i South",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "8881",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "8881",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-south",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 71,
      name: "Al Nahda (Dubai)",
      name_l1: "النهدة (دبي)",
      externalID: "5599",
      slug: "/dubai/al-nahda-dubai",
      slug_l1: "/dubai/al-nahda-dubai",
      _geoloc: {
        lat: 25.292858,
        lng: 55.372767,
      },
      geography: {
        lat: 25.292858,
        lng: 55.372767,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 71,
          level: 2,
          externalID: "5599",
          name: "Al Nahda (Dubai)",
          name_l1: "النهدة (دبي)",
          slug: "/dubai/al-nahda-dubai",
          slug_l1: "/dubai/al-nahda-dubai",
        },
      ],
      adCount: 1407,
      aliases: ["Nahda", "Al Nadha"],
      type: null,
      hasBuilding: false,
      trackID: "5599",
      roles: null,
      objectID: "71",
      _highlightResult: {
        name: {
          value: "Al Nahda (<em>Duba</em>i)",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5599",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5599",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/al-nahda-<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "Nahda",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "Al Nadha",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 79,
      name: "Dubai Investment Park (DIP)",
      name_l1: "مجمع دبي للاستثمار",
      externalID: "5241",
      slug: "/dubai/dubai-investment-park-dip",
      slug_l1: "/dubai/dubai-investment-park-dip",
      _geoloc: {
        lat: 24.971840464711,
        lng: 55.183587234481,
      },
      geography: {
        lat: 24.971840464711,
        lng: 55.183587234481,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 79,
          level: 2,
          externalID: "5241",
          name: "Dubai Investment Park (DIP)",
          name_l1: "مجمع دبي للاستثمار",
          slug: "/dubai/dubai-investment-park-dip",
          slug_l1: "/dubai/dubai-investment-park-dip",
        },
      ],
      adCount: 986,
      aliases: ["DIP", "Dubai Investments Park"],
      type: null,
      hasBuilding: false,
      trackID: "5241",
      roles: null,
      objectID: "79",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Investment Park (DIP)",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5241",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5241",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-investment-park-dip",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "DIP",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "<em>Duba</em>i Investments Park",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
        ],
      },
    },
    {
      id: 380,
      name: "Maple at Dubai Hills Estate",
      name_l1: "ميبل في دبي هيلز استيت",
      externalID: "9188",
      slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
      slug_l1: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
      _geoloc: {
        lat: 25.093024,
        lng: 55.254131,
      },
      geography: {
        lat: 25.093024,
        lng: 55.254131,
      },
      level: 3,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 53,
          level: 2,
          externalID: "8288",
          name: "Dubai Hills Estate",
          name_l1: "دبي هيلز استيت",
          slug: "/dubai/dubai-hills-estate",
          slug_l1: "/dubai/dubai-hills-estate",
        },
        {
          id: 380,
          level: 3,
          externalID: "9188",
          name: "Maple at Dubai Hills Estate",
          name_l1: "ميبل في دبي هيلز استيت",
          slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
          slug_l1: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
        },
      ],
      adCount: 797,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "9188",
      roles: null,
      objectID: "380",
      _highlightResult: {
        name: {
          value: "Maple at <em>Duba</em>i Hills Estate",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "9188",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "8288",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-hills-estate",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "9188",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/<em>duba</em>i-hills-estate/maple-at-<em>duba</em>i-hills-estate",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 5036,
      name: "Dubai Production City (IMPZ)",
      name_l1: "مدينة دبي للإنتاج",
      externalID: "5900",
      slug: "/dubai/dubai-production-city-impz",
      slug_l1: "/dubai/dubai-production-city-impz",
      _geoloc: {
        lat: 25.03265,
        lng: 55.191021,
      },
      geography: {
        lat: 25.03265,
        lng: 55.191021,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 5036,
          level: 2,
          externalID: "5900",
          name: "Dubai Production City (IMPZ)",
          name_l1: "مدينة دبي للإنتاج",
          slug: "/dubai/dubai-production-city-impz",
          slug_l1: "/dubai/dubai-production-city-impz",
        },
      ],
      adCount: 752,
      aliases: ["IMPZ", "International Media Production Zone", "DPC"],
      type: null,
      hasBuilding: false,
      trackID: "5900",
      roles: null,
      objectID: "5036",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Production City (IMPZ)",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5900",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5900",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-production-city-impz",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "IMPZ",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "International Media Production Zone",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "DPC",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 603,
      name: "Dubai Residence Complex",
      name_l1: "مجمع دبي ريزيدنس",
      externalID: "9038",
      slug: "/dubai/dubai-residence-complex",
      slug_l1: "/dubai/dubai-residence-complex",
      _geoloc: {
        lat: 25.092629,
        lng: 55.38076,
      },
      geography: {
        lat: 25.092629,
        lng: 55.38076,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 603,
          level: 2,
          externalID: "9038",
          name: "Dubai Residence Complex",
          name_l1: "مجمع دبي ريزيدنس",
          slug: "/dubai/dubai-residence-complex",
          slug_l1: "/dubai/dubai-residence-complex",
        },
      ],
      adCount: 734,
      aliases: ["Dubailand Residence Complex"],
      type: null,
      hasBuilding: false,
      trackID: "9038",
      roles: null,
      objectID: "603",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Residence Complex",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "9038",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "9038",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-residence-complex",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "<em>Duba</em>iland Residence Complex",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
        ],
      },
    },
    {
      id: 1621,
      name: "Dubai Internet City",
      name_l1: "مدينة دبي للإنترنت",
      externalID: "7934",
      slug: "/dubai/dubai-internet-city",
      slug_l1: "/dubai/dubai-internet-city",
      _geoloc: {
        lat: 25.095260063801,
        lng: 55.161272709648,
      },
      geography: {
        lat: 25.095260063801,
        lng: 55.161272709648,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 1621,
          level: 2,
          externalID: "7934",
          name: "Dubai Internet City",
          name_l1: "مدينة دبي للإنترنت",
          slug: "/dubai/dubai-internet-city",
          slug_l1: "/dubai/dubai-internet-city",
        },
      ],
      adCount: 525,
      aliases: ["Internet City Dubai", "Internet City", "DIC"],
      type: null,
      hasBuilding: false,
      trackID: "7934",
      roles: null,
      objectID: "1621",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Internet City",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "7934",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "7934",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-internet-city",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "Internet City <em>Duba</em>i",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "Internet City",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "DIC",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 95,
      name: "Dubai Media City",
      name_l1: "مدينة دبي للإعلام",
      externalID: "7935",
      slug: "/dubai/dubai-media-city",
      slug_l1: "/dubai/dubai-media-city",
      _geoloc: {
        lat: 25.094951000901,
        lng: 55.155371725559,
      },
      geography: {
        lat: 25.094951000901,
        lng: 55.155371725559,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 95,
          level: 2,
          externalID: "7935",
          name: "Dubai Media City",
          name_l1: "مدينة دبي للإعلام",
          slug: "/dubai/dubai-media-city",
          slug_l1: "/dubai/dubai-media-city",
        },
      ],
      adCount: 486,
      aliases: ["Media City", "Media City Dubai", "DMC"],
      type: null,
      hasBuilding: false,
      trackID: "7935",
      roles: null,
      objectID: "95",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Media City",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "7935",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "7935",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-media-city",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "Media City",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "Media City <em>Duba</em>i",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "DMC",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 639,
      name: "The Address Dubai Mall",
      name_l1: "العنوان دبي مول",
      externalID: "6799",
      slug: "/dubai/downtown-dubai/the-address-dubai-mall",
      slug_l1: "/dubai/downtown-dubai/the-address-dubai-mall",
      _geoloc: {
        lat: 25.199155807495,
        lng: 55.274662017822,
      },
      geography: {
        lat: 25.199155807495,
        lng: 55.274662017822,
      },
      level: 3,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 10,
          level: 2,
          externalID: "6901",
          name: "Downtown Dubai",
          name_l1: "وسط مدينة دبي",
          slug: "/dubai/downtown-dubai",
          slug_l1: "/dubai/downtown-dubai",
        },
        {
          id: 639,
          level: 3,
          externalID: "6799",
          name: "The Address Dubai Mall",
          name_l1: "العنوان دبي مول",
          slug: "/dubai/downtown-dubai/the-address-dubai-mall",
          slug_l1: "/dubai/downtown-dubai/the-address-dubai-mall",
        },
      ],
      adCount: 470,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "6799",
      roles: null,
      objectID: "639",
      _highlightResult: {
        name: {
          value: "The Address <em>Duba</em>i Mall",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "6799",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "6901",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/downtown-<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "6799",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/downtown-<em>duba</em>i/the-address-<em>duba</em>i-mall",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 16508,
      name: "SLS Dubai Hotel & Residences",
      name_l1: "فندق إس إل إس دبي",
      externalID: "12602",
      slug: "/dubai/business-bay/sls-dubai-hotel-residences",
      slug_l1: "/dubai/business-bay/sls-dubai-hotel-residences",
      _geoloc: {
        lat: 25.184561,
        lng: 55.291356,
      },
      geography: {
        lat: 25.184561,
        lng: 55.291356,
      },
      level: 3,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 54,
          level: 2,
          externalID: "5093",
          name: "Business Bay",
          name_l1: "الخليج التجاري",
          slug: "/dubai/business-bay",
          slug_l1: "/dubai/business-bay",
        },
        {
          id: 16508,
          level: 3,
          externalID: "12602",
          name: "SLS Dubai Hotel & Residences",
          name_l1: "فندق إس إل إس دبي",
          slug: "/dubai/business-bay/sls-dubai-hotel-residences",
          slug_l1: "/dubai/business-bay/sls-dubai-hotel-residences",
        },
      ],
      adCount: 321,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "12602",
      roles: null,
      objectID: "16508",
      _highlightResult: {
        name: {
          value: "SLS <em>Duba</em>i Hotel & Residences",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "12602",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5093",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/business-bay",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "12602",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/business-bay/sls-<em>duba</em>i-hotel-residences",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 1162,
      name: "Maple At Dubai Hills Estate 1",
      name_l1: "ميبل في دبي هيلز استيت 1",
      externalID: "9190",
      slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-1",
      slug_l1:
        "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-1",
      _geoloc: {
        lat: 25.093176,
        lng: 55.252487,
      },
      geography: {
        lat: 25.093176,
        lng: 55.252487,
      },
      level: 4,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 53,
          level: 2,
          externalID: "8288",
          name: "Dubai Hills Estate",
          name_l1: "دبي هيلز استيت",
          slug: "/dubai/dubai-hills-estate",
          slug_l1: "/dubai/dubai-hills-estate",
        },
        {
          id: 380,
          level: 3,
          externalID: "9188",
          name: "Maple at Dubai Hills Estate",
          name_l1: "ميبل في دبي هيلز استيت",
          slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
          slug_l1: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
        },
        {
          id: 1162,
          level: 4,
          externalID: "9190",
          name: "Maple At Dubai Hills Estate 1",
          name_l1: "ميبل في دبي هيلز استيت 1",
          slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-1",
          slug_l1:
            "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-1",
        },
      ],
      adCount: 320,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "9190",
      roles: null,
      objectID: "1162",
      _highlightResult: {
        name: {
          value: "Maple At <em>Duba</em>i Hills Estate 1",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "9190",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "8288",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-hills-estate",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "9188",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/<em>duba</em>i-hills-estate/maple-at-<em>duba</em>i-hills-estate",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "9190",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/<em>duba</em>i-hills-estate/maple-at-<em>duba</em>i-hills-estate/maple-at-<em>duba</em>i-hills-estate-1",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 1446,
      name: "The Address Residences Dubai Opera",
      name_l1: "العنوان رزيدنسز دبي أوبرا",
      externalID: "8659",
      slug: "/dubai/downtown-dubai/the-address-residences-dubai-opera",
      slug_l1: "/dubai/downtown-dubai/the-address-residences-dubai-opera",
      _geoloc: {
        lat: 25.193588,
        lng: 55.279061,
      },
      geography: {
        lat: 25.193588,
        lng: 55.279061,
      },
      level: 3,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 10,
          level: 2,
          externalID: "6901",
          name: "Downtown Dubai",
          name_l1: "وسط مدينة دبي",
          slug: "/dubai/downtown-dubai",
          slug_l1: "/dubai/downtown-dubai",
        },
        {
          id: 1446,
          level: 3,
          externalID: "8659",
          name: "The Address Residences Dubai Opera",
          name_l1: "العنوان رزيدنسز دبي أوبرا",
          slug: "/dubai/downtown-dubai/the-address-residences-dubai-opera",
          slug_l1: "/dubai/downtown-dubai/the-address-residences-dubai-opera",
        },
      ],
      adCount: 265,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "8659",
      roles: null,
      objectID: "1446",
      _highlightResult: {
        name: {
          value: "The Address Residences <em>Duba</em>i Opera",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "8659",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "6901",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/downtown-<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "8659",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/downtown-<em>duba</em>i/the-address-residences-<em>duba</em>i-opera",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 381,
      name: "Maple At Dubai Hills Estate 2",
      name_l1: "ميبل في دبي هيلز استيت 2",
      externalID: "9191",
      slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-2",
      slug_l1:
        "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-2",
      _geoloc: {
        lat: 25.098375,
        lng: 55.253429,
      },
      geography: {
        lat: 25.098375,
        lng: 55.253429,
      },
      level: 4,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 53,
          level: 2,
          externalID: "8288",
          name: "Dubai Hills Estate",
          name_l1: "دبي هيلز استيت",
          slug: "/dubai/dubai-hills-estate",
          slug_l1: "/dubai/dubai-hills-estate",
        },
        {
          id: 380,
          level: 3,
          externalID: "9188",
          name: "Maple at Dubai Hills Estate",
          name_l1: "ميبل في دبي هيلز استيت",
          slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
          slug_l1: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate",
        },
        {
          id: 381,
          level: 4,
          externalID: "9191",
          name: "Maple At Dubai Hills Estate 2",
          name_l1: "ميبل في دبي هيلز استيت 2",
          slug: "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-2",
          slug_l1:
            "/dubai/dubai-hills-estate/maple-at-dubai-hills-estate/maple-at-dubai-hills-estate-2",
        },
      ],
      adCount: 245,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "9191",
      roles: null,
      objectID: "381",
      _highlightResult: {
        name: {
          value: "Maple At <em>Duba</em>i Hills Estate 2",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "9191",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "8288",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-hills-estate",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "9188",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/<em>duba</em>i-hills-estate/maple-at-<em>duba</em>i-hills-estate",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "9191",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/<em>duba</em>i-hills-estate/maple-at-<em>duba</em>i-hills-estate/maple-at-<em>duba</em>i-hills-estate-2",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
    {
      id: 5099,
      name: "Dubai Industrial Park",
      name_l1: "مجمع دبي الصناعي",
      externalID: "5666",
      slug: "/dubai/dubai-industrial-park",
      slug_l1: "/dubai/dubai-industrial-park",
      _geoloc: {
        lat: 24.847188,
        lng: 55.078526,
      },
      geography: {
        lat: 24.847188,
        lng: 55.078526,
      },
      level: 2,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 5099,
          level: 2,
          externalID: "5666",
          name: "Dubai Industrial Park",
          name_l1: "مجمع دبي الصناعي",
          slug: "/dubai/dubai-industrial-park",
          slug_l1: "/dubai/dubai-industrial-park",
        },
      ],
      adCount: 230,
      aliases: [
        "Dubai Industrial City",
        "Industrial Park",
        "Industrial City",
        "DIC Dubai Industrial City",
        "DIC",
      ],
      type: null,
      hasBuilding: false,
      trackID: "5666",
      roles: null,
      objectID: "5099",
      _highlightResult: {
        name: {
          value: "<em>Duba</em>i Industrial Park",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "5666",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "5666",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-industrial-park",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
        aliases: [
          {
            value: "<em>Duba</em>i Industrial City",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "Industrial Park",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "Industrial City",
            matchLevel: "none",
            matchedWords: [],
          },
          {
            value: "DIC <em>Duba</em>i Industrial City",
            matchLevel: "full",
            fullyHighlighted: false,
            matchedWords: ["duba"],
          },
          {
            value: "DIC",
            matchLevel: "none",
            matchedWords: [],
          },
        ],
      },
    },
    {
      id: 17911,
      name: "Avani Palm View Dubai Hotel & Suites",
      name_l1: "فندق وأجنحة أفاني بالم فيو دبي",
      externalID: "13641",
      slug: "/dubai/dubai-media-city/avani-palm-view-dubai-hotel-suites",
      slug_l1: "/dubai/dubai-media-city/avani-palm-view-dubai-hotel-suites",
      _geoloc: {
        lat: 25.09855345235,
        lng: 55.15683248698,
      },
      geography: {
        lat: 25.09855345235,
        lng: 55.15683248698,
      },
      level: 3,
      hierarchy: [
        {
          id: 1,
          level: 0,
          externalID: "5001",
          name: "UAE",
          name_l1: "الإمارات",
          slug: "/uae",
          slug_l1: "/uae",
        },
        {
          id: 2,
          level: 1,
          externalID: "5002",
          name: "Dubai",
          name_l1: "دبي",
          slug: "/dubai",
          slug_l1: "/dubai",
        },
        {
          id: 95,
          level: 2,
          externalID: "7935",
          name: "Dubai Media City",
          name_l1: "مدينة دبي للإعلام",
          slug: "/dubai/dubai-media-city",
          slug_l1: "/dubai/dubai-media-city",
        },
        {
          id: 17911,
          level: 3,
          externalID: "13641",
          name: "Avani Palm View Dubai Hotel & Suites",
          name_l1: "فندق وأجنحة أفاني بالم فيو دبي",
          slug: "/dubai/dubai-media-city/avani-palm-view-dubai-hotel-suites",
          slug_l1: "/dubai/dubai-media-city/avani-palm-view-dubai-hotel-suites",
        },
      ],
      adCount: 209,
      aliases: [],
      type: null,
      hasBuilding: false,
      trackID: "13641",
      roles: null,
      objectID: "17911",
      _highlightResult: {
        name: {
          value: "Avani Palm View <em>Duba</em>i Hotel & Suites",
          matchLevel: "full",
          fullyHighlighted: false,
          matchedWords: ["duba"],
        },
        externalID: {
          value: "13641",
          matchLevel: "none",
          matchedWords: [],
        },
        hierarchy: [
          {
            externalID: {
              value: "5001",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/uae",
              matchLevel: "none",
              matchedWords: [],
            },
          },
          {
            externalID: {
              value: "5002",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "7935",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value: "/<em>duba</em>i/<em>duba</em>i-media-city",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
          {
            externalID: {
              value: "13641",
              matchLevel: "none",
              matchedWords: [],
            },
            slug: {
              value:
                "/<em>duba</em>i/<em>duba</em>i-media-city/avani-palm-view-<em>duba</em>i-hotel-suites",
              matchLevel: "full",
              fullyHighlighted: false,
              matchedWords: ["duba"],
            },
          },
        ],
      },
    },
  ],
  nbHits: 6335,
  page: 0,
  nbPages: 200,
  hitsPerPage: 25,
  exhaustiveNbHits: true,
  exhaustiveTypo: true,
  query: "duba",
  params: "filters=level > 0&hitsPerPage=25&page=0&query=duba",
  processingTimeMS: 6,
};
