import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";

const Home = () => (
  <>
    <Head>
      <title>Airbnb - NextJS Clone</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Header />
    </main>
  </>
);

export default Home;
